"""empty message

Revision ID: 15f2a47167cd
Revises: e166cdca1e67
Create Date: 2016-06-28 15:23:49.980099

"""

# revision identifiers, used by Alembic.
revision = '15f2a47167cd'
down_revision = 'e166cdca1e67'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    ### end Alembic commands ###
